// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecycleAPI.Services;

namespace RecycleAPI.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecycleAPI.Models.APIKey", b =>
                {
                    b.Property<int>("APIKeyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(128);

                    b.Property<bool>("Enabled");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<string>("LastName")
                        .HasMaxLength(64);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("VendorId");

                    b.HasKey("APIKeyId");

                    b.HasIndex("VendorId");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("RecycleAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .HasMaxLength(128);

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Address2")
                        .HasMaxLength(64);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(128);

                    b.Property<string>("ContactFirstName")
                        .HasMaxLength(64);

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("ItemId")
                        .HasMaxLength(36);

                    b.Property<int>("KitQuantity");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("NumberOfBatteries");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("OrderNumber")
                        .IsRequired();

                    b.Property<string>("OrderStatus")
                        .IsRequired();

                    b.Property<DateTime>("OrderStatusDate");

                    b.Property<string>("OrderTrackingNumber")
                        .HasMaxLength(64);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(24);

                    b.Property<string>("ProgramInfoId")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("ReciptTrackingNumber")
                        .HasMaxLength(64);

                    b.Property<string>("Reference1")
                        .HasMaxLength(128);

                    b.Property<string>("Reference2")
                        .HasMaxLength(128);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int?>("VendorId");

                    b.HasKey("OrderId");

                    b.HasIndex("VendorId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RecycleAPI.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsAdministrator");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("RecycleAPI.Models.APIKey", b =>
                {
                    b.HasOne("RecycleAPI.Models.Vendor", "Vendor")
                        .WithMany("Keys")
                        .HasForeignKey("VendorId");
                });

            modelBuilder.Entity("RecycleAPI.Models.Order", b =>
                {
                    b.HasOne("RecycleAPI.Models.Vendor", "Vendor")
                        .WithMany("Orders")
                        .HasForeignKey("VendorId");
                });
#pragma warning restore 612, 618
        }
    }
}
